version: '3'
services: 
  frontend:
    build: client
    ports: 
      - 8080:80
    links:
      - backend
    restart: always
  backend:
    build: server
    ports:
      - 8080
    volumes:
      - ./server/state:/state
      - ../killpop:/code
    environment:
      - ORISA_STATE_DIRECTORY=/state
      - ORISA_CODE_DIRECTORY=/code
      - ORISA_CODE_REMOTE=origin
      - ORISA_CODE_BRANCH=master
      - RUST_LOG=INFO
    restart: always