version: '3'
services: 
  frontend:
    build: client
    ports: 
      - 8080:80
    links:
      - backend
  backend:
    build: server
    ports:
      - 8080
    volumes:
      - ./server/state:/state
      - ../killpop:/code:ro
    environment:
      - ORISA_STATE_DIRECTORY=/state
      - ORISA_CODE_DIRECTORY=/code
      - RUST_LOG=INFO